version: "3.8"
services:
  expenses_db:
    container_name: expenses_db
    image: 'mysql/mysql-server:8.0'
    restart: always
    volumes:
      - ../expenses-db-data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

  expenses_backend:
    container_name: expenses_backend
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/vendor/
    depends_on:
      - expenses_db
    networks:
      - app_network

  expenses_nginx:
    container_name: expenses_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./storage:/usr/src/app/storage
      - ./public:/usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - expenses_backend
    environment:
      NGINX_FPM_HOST: expenses_backend
      NGINX_ROOT: /usr/src/app/public
    command: ln -s /usr/src/app/storage/app/public /usr/src/app/public/storage
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
